### ISSUE TITLE
Mod Compatibility with Windowlogging

### ISSUE THREAD

**Issue by HopsandBarley** [MongoTheElder/PITG#20]
I have both Pain in the Glass and Windowlogging installed.  

With vanilla panes, Windowlogging lets your place panes "inside" stairs and slabs, to give you more flexibility with window design.

When i try this with PITG versions of glass panes, the panes are invisible.  

I don't know if this is a problem with PITG or Windowlogging, so I'm putting this comment in both places.  Thanks!  Two really nice and creative mods.

**Comment by MongoTheElder** [comment]
Which version of PITG and Windowlogging are you using?

**Comment by HopsandBarley** [comment]
pitg-1.16.3-1.4.2

windowlogging-mc1.16.3_v0.0.4

using forge 36.1.4

**Comment by MongoTheElder** [comment]
Looking at the Windowlogging source, they are using the _forge:glass_pane_ tag to determine if this is a compatible block. Unfortunately, PITG panes are not compatible since they do not share the same placement behavior as vanilla panes (and are not derived from _PaneBlock_). PITG panes have the _forge:glass_pane tag_ so they can be used in crafting recipes.

I'll put a comment in the issue you created in their Git so they know what's happening.

**Comment by HopsandBarley** [comment]
Bummer.  Thanks for at least looking into it.  Appreciate the responsiveness.
