### ISSUE TITLE
Green dye Improvement

### ISSUE THREAD

**Issue by SpGilbert** [MongoTheElder/PITG#3]
Can you make it so the green dye that this mod adds can be used in all of the recipes that the green dye in the base game can craft? Most of the ways the regular green dye can be used don't appear to work with this mods green dye. This makes it less useful for the purpose of dying items.

**Comment by MongoTheElder** [comment]
I looked at this when I added the dye. The reason PITG green dye doesn't work in vanilla recipes is they use the 'minecraft:green_dye' item and not a tag that accepts any green dye.

Introduction of PITG green dye was because I didn't want to force players to find a desert biome just to get a Glazing Tool. Since this makes acquisition of green dye much easier it may decrease any difficulty element a mod or pack maker intended. By having the PITG green dye only be usable for the Glazing Tool (or any other recipe that explicitly allows alternate dyes), I sidestepped the issue. 

There are four ways I would consider implementing this:
1) Remove PITG green dye and have my recipe produce vanilla green dye
2) Create a new recipe to convert PITG green dye to vanilla
3) Modify the 9 vanilla recipes that use green dye to use the tag 'forge:dyes/green' and not reference the vanilla green dye item directly.
4) Remove PITG green dye and change the dye requirement for the Glazing Tool to another color.

Pros/Cons:
1) Pro: Doesn't touch vanilla recipes. Con: Breaks everyone that has PITG green dye in their inventory
2) Pro: Doesn't touch vanilla recipes. Con: Feels a bit hackish and just adds a second crafting step.
3) Pro: No change to any existing mechanics. Con: May introduce a conflict with other mods (like Botania) that modify vanilla recipes.
4) Pros: No need for green dye. Con: Breaks everyone that has PITG green dye in their inventory and requires new model textures.

In the future I want to make the alternate green dye recipe optional (via config) to allow pack builders control if it exists in the game.

**Comment by ZeroLevels** [comment]
@MongoTheElder
You could change the output of the PITG green dye to vanilla green dye, but not actually remove the item itself.  Then add a second glazer recipe that uses both a blue and yellow dye.

This way:
1. You can remove the dye itself at a later date, probably when more major changes are necessary anyways.
2. Nobody loses anything, as the PITG dye is still usable in other recipes due to green dye tag.
3. You don't have to make a new texture.
4. No additional conflicts.

You might also consider bumping up the output of green dye to 2 so that it follows suit with other dye-mixing recipes.  Just some thoughts. :)

**Comment by NielsPilgaard** [comment]
Any updates on this issue? :)

The PITG Green Dye is causing an issue in the modpack Enigmatica 6: https://github.com/NillerMedDild/Enigmatica6/issues/2746

**Comment by MongoTheElder** [comment]
I'm removing the dye requirement for the Glazing Tool in the next version and therefore will no longer need the custom green dye. Its crafting recipe will be removed along with all associated tags and a new recipe added to convert PITG green dye to vanilla green dye so players won't be angry that they lost items.

**Comment by NielsPilgaard** [comment]
Awesome!

**Comment by MongoTheElder** [comment]
PITG green dye has been removed from the mod
