### ISSUE TITLE
Glass Panes don't allow for particles to show through them

### ISSUE THREAD

**Issue by Ravin890** [MongoTheElder/PITG#5]
While on my testing world for my modpack I realized it was raining but your glass panes don't seem to allow that to show through them. I decided to test if vanilla glass and vanilla glass panes would ignore the particle effects but they don't, so you can tell its raining outside.
![image](https://user-images.githubusercontent.com/13302573/87740588-8bb09b00-c7b0-11ea-835a-415cb5c5d7a3.png)

Minecraft: 1.15.2
Forge: 31.2.31
Pitg: 1.4.0

**Comment by MongoTheElder** [comment]
Thanks for pointing this out, I'll take a look. I'm not doing anything special with transparency rendering, but I may have a setting turned off.

**Comment by MongoTheElder** [comment]
It turns out that colored vanilla glass blocks and panes have this same behavior. The clear varieties are rendered on the Cutout layer but the colored ones are on the Translucent layer which apparently doesn't show particles. I had all mine on the Translucent layer.

I'll update the mod to make the clear varieties render on the Cutout layer so they behave the same as vanilla.

**Comment by MongoTheElder** [comment]
1.15.2-1.4.1 released

**Comment by Ravin890** [comment]
good to know (I didn't test colored variations myself and yay for release~)
